import type { HiraganaLesson } from './LessonData';

// HiraganaLesson 타입을 재사용 (구조 동일)
const KATAKANA_LESSONS: HiraganaLesson[] = [
  {
    id: 'katakana-a',
    title: 'ア행 — 모음',
    titleJa: 'ア行',
    description: '카타카나 5가지 기본 모음을 배워보세요',
    icon: '⭐',
    xpReward: 20,
    characters: [
      {
        char: 'ア',
        romaji: 'a',
        exampleWord: 'アメリカ',
        exampleRomaji: 'amerika',
        meaning: '미국',
      },
      {
        char: 'イ',
        romaji: 'i',
        exampleWord: 'イギリス',
        exampleRomaji: 'igirisu',
        meaning: '영국',
      },
      {
        char: 'ウ',
        romaji: 'u',
        exampleWord: 'ウイスキー',
        exampleRomaji: 'uisukii',
        meaning: '위스키',
      },
      {
        char: 'エ',
        romaji: 'e',
        exampleWord: 'エレベーター',
        exampleRomaji: 'erebeetaa',
        meaning: '엘리베이터',
      },
      {
        char: 'オ',
        romaji: 'o',
        exampleWord: 'オレンジ',
        exampleRomaji: 'orenji',
        meaning: '오렌지',
      },
    ],
  },
  {
    id: 'katakana-ka',
    title: 'カ행',
    titleJa: 'カ行',
    description: 'K 카타카나를 배워보세요',
    icon: '🌟',
    xpReward: 25,
    characters: [
      {
        char: 'カ',
        romaji: 'ka',
        exampleWord: 'カメラ',
        exampleRomaji: 'kamera',
        meaning: '카메라',
      },
      {
        char: 'キ',
        romaji: 'ki',
        exampleWord: 'キムチ',
        exampleRomaji: 'kimuchi',
        meaning: '김치',
      },
      {
        char: 'ク',
        romaji: 'ku',
        exampleWord: 'クラス',
        exampleRomaji: 'kurasu',
        meaning: '클래스',
      },
      {
        char: 'ケ',
        romaji: 'ke',
        exampleWord: 'ケーキ',
        exampleRomaji: 'keeki',
        meaning: '케이크',
      },
      {
        char: 'コ',
        romaji: 'ko',
        exampleWord: 'コーヒー',
        exampleRomaji: 'koohii',
        meaning: '커피',
      },
    ],
  },
  {
    id: 'katakana-sa',
    title: 'サ행',
    titleJa: 'サ行',
    description: 'S 카타카나를 배워보세요',
    icon: '💫',
    xpReward: 25,
    characters: [
      {
        char: 'サ',
        romaji: 'sa',
        exampleWord: 'サラダ',
        exampleRomaji: 'sarada',
        meaning: '샐러드',
      },
      {
        char: 'シ',
        romaji: 'shi',
        exampleWord: 'シャツ',
        exampleRomaji: 'shatsu',
        meaning: '셔츠',
      },
      {
        char: 'ス',
        romaji: 'su',
        exampleWord: 'スマホ',
        exampleRomaji: 'sumaho',
        meaning: '스마트폰',
      },
      {
        char: 'セ',
        romaji: 'se',
        exampleWord: 'セーター',
        exampleRomaji: 'seetaa',
        meaning: '스웨터',
      },
      { char: 'ソ', romaji: 'so', exampleWord: 'ソファ', exampleRomaji: 'sofa', meaning: '소파' },
    ],
  },
  {
    id: 'katakana-ta',
    title: 'タ행',
    titleJa: 'タ行',
    description: 'T 카타카나를 배워보세요',
    icon: '✨',
    xpReward: 25,
    characters: [
      {
        char: 'タ',
        romaji: 'ta',
        exampleWord: 'タクシー',
        exampleRomaji: 'takushii',
        meaning: '택시',
      },
      {
        char: 'チ',
        romaji: 'chi',
        exampleWord: 'チーズ',
        exampleRomaji: 'chiizu',
        meaning: '치즈',
      },
      { char: 'ツ', romaji: 'tsu', exampleWord: 'ツアー', exampleRomaji: 'tsuaa', meaning: '투어' },
      {
        char: 'テ',
        romaji: 'te',
        exampleWord: 'テレビ',
        exampleRomaji: 'terebi',
        meaning: '텔레비전',
      },
      {
        char: 'ト',
        romaji: 'to',
        exampleWord: 'トイレ',
        exampleRomaji: 'toire',
        meaning: '화장실',
      },
    ],
  },
  {
    id: 'katakana-na',
    title: 'ナ행',
    titleJa: 'ナ行',
    description: 'N 카타카나를 배워보세요',
    icon: '🔷',
    xpReward: 25,
    characters: [
      {
        char: 'ナ',
        romaji: 'na',
        exampleWord: 'ナイフ',
        exampleRomaji: 'naifu',
        meaning: '나이프',
      },
      {
        char: 'ニ',
        romaji: 'ni',
        exampleWord: 'ニュース',
        exampleRomaji: 'nyuusu',
        meaning: '뉴스',
      },
      {
        char: 'ヌ',
        romaji: 'nu',
        exampleWord: 'ヌードル',
        exampleRomaji: 'nuudoru',
        meaning: '국수',
      },
      {
        char: 'ネ',
        romaji: 'ne',
        exampleWord: 'ネクタイ',
        exampleRomaji: 'nekutai',
        meaning: '넥타이',
      },
      { char: 'ノ', romaji: 'no', exampleWord: 'ノート', exampleRomaji: 'nooto', meaning: '노트' },
    ],
  },
  {
    id: 'katakana-ha',
    title: 'ハ행',
    titleJa: 'ハ行',
    description: 'H 카타카나를 배워보세요',
    icon: '🔶',
    xpReward: 25,
    characters: [
      {
        char: 'ハ',
        romaji: 'ha',
        exampleWord: 'ハンバーガー',
        exampleRomaji: 'hanbaagaa',
        meaning: '햄버거',
      },
      {
        char: 'ヒ',
        romaji: 'hi',
        exampleWord: 'ヒーター',
        exampleRomaji: 'hiitaa',
        meaning: '히터',
      },
      {
        char: 'フ',
        romaji: 'fu',
        exampleWord: 'フランス',
        exampleRomaji: 'furansu',
        meaning: '프랑스',
      },
      {
        char: 'ヘ',
        romaji: 'he',
        exampleWord: 'ヘリコプター',
        exampleRomaji: 'herikoptaa',
        meaning: '헬리콥터',
      },
      { char: 'ホ', romaji: 'ho', exampleWord: 'ホテル', exampleRomaji: 'hoteru', meaning: '호텔' },
    ],
  },
  {
    id: 'katakana-ma',
    title: 'マ행',
    titleJa: 'マ行',
    description: 'M 카타카나를 배워보세요',
    icon: '💎',
    xpReward: 25,
    characters: [
      {
        char: 'マ',
        romaji: 'ma',
        exampleWord: 'マスク',
        exampleRomaji: 'masuku',
        meaning: '마스크',
      },
      { char: 'ミ', romaji: 'mi', exampleWord: 'ミルク', exampleRomaji: 'miruku', meaning: '우유' },
      {
        char: 'ム',
        romaji: 'mu',
        exampleWord: 'ムービー',
        exampleRomaji: 'muubii',
        meaning: '영화',
      },
      {
        char: 'メ',
        romaji: 'me',
        exampleWord: 'メニュー',
        exampleRomaji: 'menyuu',
        meaning: '메뉴',
      },
      { char: 'モ', romaji: 'mo', exampleWord: 'モデル', exampleRomaji: 'moderu', meaning: '모델' },
    ],
  },
  {
    id: 'katakana-ya',
    title: 'ヤ행',
    titleJa: 'ヤ行',
    description: 'Y 카타카나를 배워보세요',
    icon: '🔹',
    xpReward: 20,
    characters: [
      { char: 'ヤ', romaji: 'ya', exampleWord: 'ヤフー', exampleRomaji: 'yahuu', meaning: '야후' },
      {
        char: 'ユ',
        romaji: 'yu',
        exampleWord: 'ユニフォーム',
        exampleRomaji: 'yunifoomu',
        meaning: '유니폼',
      },
      {
        char: 'ヨ',
        romaji: 'yo',
        exampleWord: 'ヨーグルト',
        exampleRomaji: 'yooguruto',
        meaning: '요구르트',
      },
    ],
  },
  {
    id: 'katakana-ra',
    title: 'ラ행',
    titleJa: 'ラ行',
    description: 'R 카타카나를 배워보세요',
    icon: '🔸',
    xpReward: 25,
    characters: [
      {
        char: 'ラ',
        romaji: 'ra',
        exampleWord: 'ラーメン',
        exampleRomaji: 'raamen',
        meaning: '라멘',
      },
      {
        char: 'リ',
        romaji: 'ri',
        exampleWord: 'リモコン',
        exampleRomaji: 'rimokon',
        meaning: '리모컨',
      },
      { char: 'ル', romaji: 'ru', exampleWord: 'ルール', exampleRomaji: 'ruuru', meaning: '규칙' },
      {
        char: 'レ',
        romaji: 're',
        exampleWord: 'レストラン',
        exampleRomaji: 'resutoran',
        meaning: '레스토랑',
      },
      {
        char: 'ロ',
        romaji: 'ro',
        exampleWord: 'ロボット',
        exampleRomaji: 'robotto',
        meaning: '로봇',
      },
    ],
  },
  {
    id: 'katakana-wa',
    title: 'ワ행 + ン',
    titleJa: 'ワ行',
    description: 'W 카타카나와 받침 ン을 배워보세요',
    icon: '🔺',
    xpReward: 20,
    characters: [
      { char: 'ワ', romaji: 'wa', exampleWord: 'ワイン', exampleRomaji: 'wain', meaning: '와인' },
      {
        char: 'ヲ',
        romaji: 'wo',
        exampleWord: 'ヲタク',
        exampleRomaji: 'wotaku',
        meaning: '오타쿠',
      },
      { char: 'ン', romaji: 'n', exampleWord: 'パン', exampleRomaji: 'pan', meaning: '빵' },
    ],
  },
];

export default KATAKANA_LESSONS;
